"""auth users table (SB2/US7/T1)

Revision ID: 9fa0565135f6
Revises: d6fbea008c73
Create Date: 2026-09-12 17:15:56.060466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa0565135f6'
down_revision: Union[str, Sequence[str], None] = 'd6fbea008c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'COORDINATOR', 'FACULTY', 'STUDENT', name='user_role_enum'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'SYSTEM_ADMIN' AND department_id IS NULL) OR (role != 'SYSTEM_ADMIN' AND department_id IS NOT NULL)", name='ck_users_department_scope'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')

    sa.Enum(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

