"""academic hierarchy schema (SB2/US2/T2)

Revision ID: d6fbea008c73
Revises: 
Create Date: 2026-09-12 03:01:18.243383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fbea008c73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_academic_years_date_order'),
    sa.PrimaryKeyConstraint('academic_year_id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('semesters',
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('semester_number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.CheckConstraint('semester_number BETWEEN 1 AND 8', name='ck_semesters_number_range'),
    sa.PrimaryKeyConstraint('semester_id'),
    sa.UniqueConstraint('semester_number')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('required_weekly_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.CheckConstraint('required_weekly_hours > 0', name='ck_courses_hours_positive'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('department_id', 'semester_id', 'code', name='uq_courses_dept_sem_code')
    )
    op.create_table('participant_groups',
    sa.Column('participant_group_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('combined_strength', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('participant_group_id')
    )
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('student_strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('student_strength > 0', name='ck_sections_strength_positive'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('department_id', 'academic_year_id', 'semester_id', 'name', name='uq_sections_dept_year_sem_name')
    )
    op.create_table('course_session_type_configs',
    sa.Column('course_session_type_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('LECTURE', 'PRACTICAL', 'TUTE_ASSIGNMENT', 'PROJECT', 'SEMINAR', 'EVENT', name='session_type_enum'), nullable=False),
    sa.Column('sessions_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('required_resource_type', sa.Enum('CLASSROOM', 'LABORATORY', 'SEMINAR_HALL', 'AUDITORIUM', name='resource_type_enum'), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name='ck_cstc_duration_positive'),
    sa.CheckConstraint('sessions_per_week > 0', name='ck_cstc_sessions_per_week_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('course_session_type_id'),
    sa.UniqueConstraint('course_id', 'session_type', name='uq_course_session_type_configs_course_type')
    )
    op.create_table('sub_batches',
    sa.Column('subbatch_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('student_strength', sa.Integer(), nullable=False),
    sa.Column('practical_group_info', sa.Text(), nullable=True),
    sa.CheckConstraint('student_strength > 0', name='ck_subbatches_strength_positive'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('subbatch_id'),
    sa.UniqueConstraint('section_id', 'name', name='uq_subbatches_section_name')
    )
    op.create_index('ix_subbatches_section_id', 'sub_batches', ['section_id'], unique=False)
    op.create_table('participant_group_members',
    sa.Column('participant_group_member_id', sa.Integer(), nullable=False),
    sa.Column('participant_group_id', sa.Integer(), nullable=False),
    sa.Column('subbatch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_group_id'], ['participant_groups.participant_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subbatch_id'], ['sub_batches.subbatch_id'], ),
    sa.PrimaryKeyConstraint('participant_group_member_id'),
    sa.UniqueConstraint('participant_group_id', 'subbatch_id', name='uq_pgm_group_subbatch')
    )
    op.create_index('ix_pgm_subbatch_id', 'participant_group_members', ['subbatch_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_session_type_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('LECTURE', 'PRACTICAL', 'TUTE_ASSIGNMENT', 'PROJECT', 'SEMINAR', 'EVENT', name='session_type_enum'), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('required_resource_type', sa.Enum('CLASSROOM', 'LABORATORY', 'SEMINAR_HALL', 'AUDITORIUM', name='resource_type_enum'), nullable=True),
    sa.Column('required_capacity', sa.Integer(), nullable=True),
    sa.Column('scheduled_day', sa.SmallInteger(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'FEASIBLE', 'RESOURCE_ALLOCATED', 'VALIDATED', 'CANCELLED', 'REPLACED_BY_EVENT', name='session_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_day IS NULL OR scheduled_day BETWEEN 1 AND 7', name='ck_sessions_day_range'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['course_session_type_id'], ['course_session_type_configs.course_session_type_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_sessions_course_session_type_id', 'sessions', ['course_session_type_id'], unique=False)
    op.create_index('ix_sessions_dept_day_start', 'sessions', ['department_id', 'scheduled_day', 'start_time'], unique=False)
    op.create_table('session_faculty',
    sa.Column('session_faculty_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_faculty_id'),
    sa.UniqueConstraint('session_id', 'faculty_id', name='uq_session_faculty_pair')
    )
    op.create_index('ix_session_faculty_faculty_id', 'session_faculty', ['faculty_id'], unique=False)
    op.create_table('session_participant_groups',
    sa.Column('session_participant_group_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_group_id'], ['participant_groups.participant_group_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_participant_group_id'),
    sa.UniqueConstraint('session_id', 'participant_group_id', name='uq_spg_session_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_participant_groups')
    op.drop_index('ix_session_faculty_faculty_id', table_name='session_faculty')
    op.drop_table('session_faculty')
    op.drop_index('ix_sessions_dept_day_start', table_name='sessions')
    op.drop_index('ix_sessions_course_session_type_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_pgm_subbatch_id', table_name='participant_group_members')
    op.drop_table('participant_group_members')
    op.drop_index('ix_subbatches_section_id', table_name='sub_batches')
    op.drop_table('sub_batches')
    op.drop_table('course_session_type_configs')
    op.drop_table('sections')
    op.drop_table('participant_groups')
    op.drop_table('courses')
    op.drop_table('semesters')
    op.drop_table('departments')
    op.drop_table('academic_years')
    # ### end Alembic commands ###

    # Autogenerate does NOT emit DROP TYPE for Postgres ENUMs on drop_table
    # (op.drop_table is raw DDL, disconnected from the ORM-level metadata
    # drop event that normally cleans these up). Without this, a
    # downgrade -> upgrade round trip fails with "type already exists".
    # Order doesn't matter for DROP TYPE (no inter-enum dependencies).
    sa.Enum(name='session_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='resource_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='session_type_enum').drop(op.get_bind(), checkfirst=True)
